server:
  port: 8082
spring:
  application:
    name: demo-client2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#
##请求处理的超时时间
#ribbon.ReadTimeout: 120000
##请求连接的超时时间
#ribbon.ConnectTimeout: 30000
#
#feign.hystrix.enabled: true
##hystrix 熔断机制
#hystrix:
#  shareSecurityContext: true
#  command:
#    default:
#      circuitBreaker:
#        sleepWindowInMilliseconds: 100000
#        forceClosed: true
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 600000

#
#feign:
#  hystrix:
#    enabled: false
#  client:
#    config:
#      default:
#        connectTimeout: 2000
#        readTimeout: 5000
#        loggerLevel: FULL
#        retryer: feign.Retryer.Default
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE

# 记录 feign 调用的日志
logging:
  level:
    com.xkcoding.feign.ConsumerClientFeign: debug
